-- сделал в postgresql для mssql решение аналогично

Select p."Name" as ProductName, 
	      c."Name" as CategoryName
     from products p
left join productcategory  pc on pc.productid  = p.Id
left join categories c on pc.categoryid = c.Id
 order by p."Name" , c."Name" 
 
 /*
 результат:
 productname|categoryname|
-----------+------------+
a          |a           |
a          |aa          |
b          |            |
c          |c           |

 */

 /*
 таблицы:

 CREATE TABLE public.products (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Name" varchar NOT NULL
);
CREATE TABLE public.categories (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Name" varchar NOT NULL
);
CREATE TABLE public.productcategory (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	productid int4 NOT NULL,
	categoryid int4 NOT NULL
);

 */